language: csharp
solution: Interactr/Interactr.sln
before_install:
  - wget https://github.com/nunit/nunit-console/releases/download/3.8/NUnit.Console-3.8.0.zip
  - unzip NUnit.Console-3.8.0.zip -d nunit
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
script:
  - msbuild /p:Configuration=Release Interactr/Interactr.sln
  - mono nunit/nunit3-console.exe ./Interactr.Tests/bin/Release/Interactr.Tests.dll
notifications:
  email: false
